collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: Armin Sarkozi
  links:
    - https://github.com/arminsarkozi

domain: arminsarkozi.github.io
url: https://arminsarkozi.github.io
  baseurl: ""